Update version constraint on public_suffix
I noticed this change to Gemfile.lock after running `bundle install`
locally and it also seems to be causing a problem in CI[1]:

> Bundler found incorrect dependencies in the lockfile for addressable-2.9.0
> Error: The process '/opt/hostedtoolcache/Ruby/3.4.2/x64/bin/bundle' failed with exit code 41

[1]: https://github.com/freerange/site/actions/runs/26641477268/job/78517012421