Add missing require to avoid error running rake task.
I was seeing the following error:

    undefined method `parse' for Date:Class

This might be because I was running an older version of Ruby (1.9.3) than
@chrisroos.