Fix broken home page.
I removed the harmonia project snip in the last commit, but this page still
refers to it. This was causing the following exception:

    NoMethodError: undefined method `images' for nil:NilClass project:9:in `handle'
    ~/Code/freerange/site/.bundle/gems/ruby/1.9.1/bundler/gems/vanilla-rb-586acf13dd8f/lib/vanilla/renderers/ruby.rb:35:in `process_text'
    ~/Code/freerange/site/.bundle/gems/ruby/1.9.1/bundler/gems/vanilla-rb-586acf13dd8f/lib/vanilla/renderers/base.rb:99:in `render_without_including_snips'
    ~/Code/freerange/site/.bundle/gems/ruby/1.9.1/bundler/gems/vanilla-rb-586acf13dd8f/lib/vanilla/renderers/base.rb:87:in `render'
    ~/Code/freerange/site/.bundle/gems/ruby/1.9.1/bundler/gems/vanilla-rb-586acf13dd8f/lib/vanilla/app.rb:70:in `block in render'